spring:
  profile: dev
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:sk-dummy-for-test}

  datasource:
    postgres:
      url: jdbc:postgresql://115.190.50.51:15432/postgres
      username: postgres
      password: 123456
      driver-class-name: org.postgresql.Driver

ai:
  chat:
    model: deepseek-v4-pro
    base-url: https://api.deepseek.com
    api-key: ${DEEPSEEK_API_KEY}
    completionsPath: /chat/completions

  embedding:
    model: text-embedding-v4
    base-url: https://dashscope.aliyuncs.com
    api-key: ${BAILIAN_API_KEY}
    embeddingsPath: /compatible-mode/v1/embeddings
    dimensions: 1024

minio:
  endpoint: http://115.190.50.51/:9000
  access-key: a2Eyec0iYiNU80UXThsM
  secret-key: 2GPyC530bZK5DSr6ASOzUCfM317pL9xymd2djf5c
  bucket-name: rag




